--  generated by WisiToken Wisi from ada.wy
--  command line: wisi-generate.exe -v 1 --output_language Ada_Emacs --lexer re2c --interface process ada.wy
--

with WisiToken.Syntax_Trees;
with WisiToken.LR.Parser;
package Ada_Process_Main is

   procedure Create_Parser
     (Parser                       :    out WisiToken.LR.Parser.Parser;
      Language_Fixes               : in     WisiToken.LR.Parser.Language_Fixes_Access;
      Language_Constrain_Terminals : in     WisiToken.LR.Parser.Language_Constrain_Terminals_Access;
      Language_String_ID_Set       : in     WisiToken.LR.Parser.Language_String_ID_Set_Access;
      Algorithm                    : in     WisiToken.Generator_Algorithm_Type;
      Trace                        : not null access WisiToken.Trace'Class;
      User_Data                    : in     WisiToken.Syntax_Trees.User_Data_Access);

end Ada_Process_Main;
