name = "wisitoken"
description = "Generalized LALR and packrat parser generator, with robust error correction"
tags = ["parser generator", "LALR", "packrat", "generalized", "error recovery"]
version = "4.0"
licenses = "GPL-3.0-or-later"

authors = ["Stephen Leake"]
maintainers = ["Stephen Leake <stephen_leake@stephe-leake.org>"]
maintainers-logins = ["stephe-ada-guru"]

website = "https://stephe-leake.org/ada/wisitoken.html"

project-files = ["build/wisitoken_alire.gpr"]
[[depends-on]]
gnatcoll = "^22.0.0"
stephes_ada_library = "~3.7"

[[pins]]
stephes_ada_library = { path='../org.stephe_leake.sal' }
