name = "emacs_ada_mode"
description = "Parser for Emacs ada-mode"
tags = ["emacs", "ada-mode"]
version = "8.0"
licenses = "GPL-3.0-or-later"

authors = ["Stephen Leake"]
maintainers = ["Stephen Leake <stephen_leake@stephe-leake.org>"]
maintainers-logins = ["stephe-ada-guru"]

website = "https://www.nongnu.org/ada-mode/"

project-files = ["emacs_ada_mode.gpr"]

executables = ["ada_mode_wisi_lalr_parse",
               "ada_mode_wisi_lr1_parse"
              ]

[[depends-on]]
stephes_ada_library = "~3.7.0"
wisitoken = "~4.0.0"
emacs_wisi = "~4.1.0"
re2c = ">=2.9"

[[pins]]
stephes_ada_library  = { path='../org.stephe_leake.sal' }
wisitoken            = { path='../org.wisitoken' }
emacs_wisi           = { path='../org.emacs.wisi' }
re2c                 = { path='../re2c_alire' }

[[actions]]
type = "pre-build"
command = ["make", "-f", "Alire.make", "ada_annex_p_re2c.c"]

