name = "emacs_wisi"
description = "Ada code for Emacs wisi ELPA package"
version = "4.1.0-beta"

authors = ["Stephen Leake"]
maintainers = ["Stephen Leake <stephen_leake@stephe-leake.org>"]
maintainers-logins = ["stephe-ada-guru"]

project-files = ["wisi_alire.gpr"]

[[depends-on]]
stephes_ada_library = "3.7"
wisitoken = "4.0"

[[pins]]
stephes_ada_library = { path='../org.stephe_leake.sal' }
wisitoken = { path='../org.wisitoken' }
