name = "wisitoken"
description = "Generalized error correcting LALR and packrat parser generator"
tags = ["parser", "generator", "generalized"]
version = "4.1.0"
licenses = "GPL-3.0-or-later"

authors = ["Stephen Leake"]
maintainers = ["Stephen Leake <stephen_leake@stephe-leake.org>"]
maintainers-logins = ["stephe-ada-guru"]

website = "https://stephe-leake.org/ada/wisitoken.html"

project-files = ["build/wisitoken_alire.gpr", "build/wisitoken_alire_mains.gpr"]

#  We use ".exe" extension even on non-Windows, to simplify the makefiles.
executables = ["wisitoken-bnf-generate.exe"]

[[depends-on]]
gnatcoll = "^22.0.0"
stephes_ada_library = "~3.7.2"

# We use Ada 2022 syntax, so need the -gnat2022 switch; introduced in gnat FSF 11, Community 2021. 
gnat = "(>=11 & <2000) | >=2021"

[[pins]]
stephes_ada_library = { path='../org.stephe_leake.sal' }
