name = "emacs_wisi"
description = "Ada code for Emacs wisi ELPA package"
tags = ["emacs", "indent", "project", "compile", "xref"]
version = "4.1.1"
licenses = "GPL-3.0-or-later"

authors = ["Stephen Leake"]
maintainers = ["Stephen Leake <stephen_leake@stephe-leake.org>"]
maintainers-logins = ["stephe-ada-guru"]

website = "https://elpa.gnu.org/packages/wisi.html"

project-files = ["wisi_alire.gpr"]

[[depends-on]]
stephes_ada_library = "~3.7.0"
wisitoken = "~4.0.0"

# We use Ada 2022 syntax, so need the -gnat2022 switch; introduced in gnat FSF 11, Community 2021. 
gnat = ">=11 & <2000"

[[pins]]
stephes_ada_library = { path='../org.stephe_leake.sal' }
wisitoken = { path='../org.wisitoken' }
