name = "emacs_gpr_query"
description = "Emacs xref backend using information output by GNAT compiler."
tags = ["emacs", "xref"]
version = "1.0"
licenses = "GPL-3.0-or-later"

authors = ["Stephen Leake"]
maintainers = ["Stephen Leake <stephen_leake@stephe-leake.org>"]
maintainers-logins = ["stephe-ada-guru"]

project-files = ["emacs_gpr_query.gpr"]

executables = ["gpr_query.adb"]

[[depends-on]]
gnatcoll = "^22.0.0"
gnatcoll_sqlite = "^22.0.0"
gnatcoll_xref = "^22.0.0"
