name = "stephes_ada_library"
description = "Stephe's Ada library; miscellaneous useful stuff."
tags = ["containers", "trees"]
version = "3.7"
licenses = "GPL-3.0-or-later"

authors = ["Stephen Leake"]
maintainers = ["Stephen Leake <stephen_leake@stephe-leake.org>"]
maintainers-logins = ["stephe-ada-guru"]

website = "https://stephe-leake.org/ada/sal.html"

project-files = ["build/stephes_ada_library.gpr"]
