name = "stephes_ada_library"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Stephen Leake"]
maintainers = ["Stephen Leake <stephen_leake@stephe-leake.org>"]
maintainers-logins = ["stephe-ada-guru"]

project-files = ["build/stephes_ada_library.gpr"]