name = "wisitoken"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Stephen Leake"]
maintainers = ["Stephen Leake <stephen_leake@stephe-leake.org>"]
maintainers-logins = ["stephe-ada-guru"]

project-files = ["build/wisitoken_alire.gpr"]
[[depends-on]]
stephes_ada_library = "~0.1.0-dev"
[[pins]]
stephes_ada_library = { path='../org.stephe_leake.sal.stephe-2' }
[[depends-on]]
gnatcoll = "^22.0.0"
