--  generated by WisiToken Wisi from gpr.wy
--  with command line: wisi-generate.exe -v 1 --output_language Ada_Emacs --lexer re2c --interface process --enum gpr.wy
--
--  Copyright (C) 2013 - 2015 Free Software Foundation, Inc.

--  This program is free software; you can redistribute it and/or
--  modify it under the terms of the GNU General Public License as
--  published by the Free Software Foundation; either version 3, or (at
--  your option) any later version.
--
--  This software is distributed in the hope that it will be useful,
--  but WITHOUT ANY WARRANTY; without even the implied warranty of
--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
--  General Public License for more details.
--
--  You should have received a copy of the GNU General Public License
--  along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>.

with WisiToken.Lexer.re2c;
with WisiToken.Parser.LR.Parser;
with WisiToken.Wisi_Runtime; use WisiToken.Wisi_Runtime;
with WisiToken.Wisi_Runtime.Gpr; use WisiToken.Wisi_Runtime.Gpr;
with gpr_re2c_c;
package body Gpr_Process is

   use all type Motion_Param_Array;

   package Lexer is new WisiToken.Lexer.re2c
     (gpr_re2c_c.New_Lexer,
      gpr_re2c_c.Free_Lexer,
      gpr_re2c_c.Reset_Lexer,
      gpr_re2c_c.Next_Token);

   procedure aggregate_g_0
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         null;
      when Face =>
         null;
      when Indent =>
         Indent_Action_0 (Parse_Data, Nonterm, Tokens, ((False, (Simple, (Int, 0))), (False, (Simple, (Anchored_0, 1, 1))), (False, (Simple, (Anchored_0, 1, 0)))));
      end case;
   end aggregate_g_0;

   procedure attribute_declaration_0
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, ((1, Statement_Start), (5, Statement_End)));
      when Face =>
         Face_Apply_Action (Parse_Data, Nonterm, Tokens, (1 => (2, 1, 0)));
      when Indent =>
         Indent_Action_0 (Parse_Data, Nonterm, Tokens, ((False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0)))));
      end case;
   end attribute_declaration_0;

   procedure attribute_declaration_1
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, ((1, Statement_Start), (8, Statement_End)));
      when Face =>
         Face_Apply_Action (Parse_Data, Nonterm, Tokens, (1 => (2, 1, 0)));
      when Indent =>
         Indent_Action_0 (Parse_Data, Nonterm, Tokens, ((False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, Gpr_Indent_Broken - 1))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, Gpr_Indent_Broken - 1))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0)))));
      end case;
   end attribute_declaration_1;

   procedure attribute_declaration_2
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, ((1, Statement_Start), (8, Statement_End)));
      when Face =>
         null;
      when Indent =>
         Indent_Action_0 (Parse_Data, Nonterm, Tokens, ((False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, Gpr_Indent_Broken - 1))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, Gpr_Indent_Broken - 1))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0)))));
      end case;
   end attribute_declaration_2;

   procedure case_statement_0
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, ((1, Statement_Start), (7, Statement_End)));
         Containing_Action (Parse_Data, Nonterm, Tokens, 1, 4);
      when Face =>
         null;
      when Indent =>
         Indent_Action_0 (Parse_Data, Nonterm, Tokens, ((False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0))), (True, (Simple, (Int, Gpr_Indent_When)), (Simple, (Int, Gpr_Indent_When))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, 0)))));
      end case;
   end case_statement_0;

   procedure case_item_0
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, (1 => (1, Motion)));
      when Face =>
         null;
      when Indent =>
         Indent_Action_0 (Parse_Data, Nonterm, Tokens, ((False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, Gpr_Indent))), (False, (Simple, (Int, Gpr_Indent)))));
      end case;
   end case_item_0;

   procedure package_spec_0
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, ((1, Statement_Start), (7, Statement_End)));
         Containing_Action (Parse_Data, Nonterm, Tokens, 1, 4);
      when Face =>
         Face_Apply_Action (Parse_Data, Nonterm, Tokens, ((2, 1, 0), (6, 1, 0)));
      when Indent =>
         Indent_Action_0 (Parse_Data, Nonterm, Tokens, ((False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0))), (True, (Simple, (Int, Gpr_Indent)), (Simple, (Int, Gpr_Indent))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, 0)))));
      end case;
   end package_spec_0;

   procedure package_extension_0
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, ((1, Statement_Start), (9, Statement_End)));
         Containing_Action (Parse_Data, Nonterm, Tokens, 1, 6);
      when Face =>
         Face_Apply_Action (Parse_Data, Nonterm, Tokens, ((2, 1, 0), (8, 1, 0)));
      when Indent =>
         Indent_Action_0 (Parse_Data, Nonterm, Tokens, ((False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0))), (True, (Simple, (Int, Gpr_Indent)), (Simple, (Int, Gpr_Indent))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, 0)))));
      end case;
   end package_extension_0;

   procedure package_renaming_0
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, ((1, Statement_Start), (5, Statement_End)));
      when Face =>
         Face_Apply_Action (Parse_Data, Nonterm, Tokens, ((2, 1, 0), (4, 1, 0)));
      when Indent =>
         null;
      end case;
   end package_renaming_0;

   procedure project_extension_0
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, ((1, Statement_Start), (9, Statement_End)));
         Containing_Action (Parse_Data, Nonterm, Tokens, 1, 6);
      when Face =>
         Face_Apply_Action (Parse_Data, Nonterm, Tokens, ((2, 1, 0), (8, 1, 0)));
      when Indent =>
         Indent_Action_0 (Parse_Data, Nonterm, Tokens, ((False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0))), (True, (Simple, (Int, Gpr_Indent)), (Simple, (Int, Gpr_Indent))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, 0)))));
      end case;
   end project_extension_0;

   procedure simple_declarative_item_0
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, ((1, Statement_Start), (4, Statement_End)));
      when Face =>
         null;
      when Indent =>
         Indent_Action_0 (Parse_Data, Nonterm, Tokens, ((False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0)))));
      end case;
   end simple_declarative_item_0;

   procedure simple_declarative_item_1
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, ((1, Statement_Start), (6, Statement_End)));
      when Face =>
         null;
      when Indent =>
         Indent_Action_0 (Parse_Data, Nonterm, Tokens, ((False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0)))));
      end case;
   end simple_declarative_item_1;

   procedure simple_declarative_item_4
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, ((1, Statement_Start), (2, Statement_End)));
      when Face =>
         null;
      when Indent =>
         null;
      end case;
   end simple_declarative_item_4;

   procedure simple_project_declaration_0
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, ((1, Statement_Start), (7, Statement_End)));
         Containing_Action (Parse_Data, Nonterm, Tokens, 1, 4);
      when Face =>
         Face_Apply_Action (Parse_Data, Nonterm, Tokens, ((2, 1, 0), (6, 1, 0)));
      when Indent =>
         Indent_Action_0 (Parse_Data, Nonterm, Tokens, ((False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0))), (True, (Simple, (Int, Gpr_Indent)), (Simple, (Int, Gpr_Indent))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, 0))), (False, (Simple, (Int, 0)))));
      end case;
   end simple_project_declaration_0;

   procedure typed_string_declaration_0
    (Nonterm : in WisiToken.Augmented_Token'Class;
     Index   : in Natural;
     Tokens  : in WisiToken.Augmented_Token_Array)
   is
      pragma Unreferenced (Index);
   begin
      case Parse_Data.Parse_Action is
      when Navigate =>
         Statement_Action (Parse_Data, Nonterm, Tokens, ((1, Statement_Start), (5, Statement_End)));
      when Face =>
         null;
      when Indent =>
         Indent_Action_0 (Parse_Data, Nonterm, Tokens, ((False, (Simple, (Int, 0))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, Gpr_Indent_Broken))), (False, (Simple, (Int, 0)))));
      end case;
   end typed_string_declaration_0;

   procedure Create_Parser
     (Parser         :    out WisiToken.Parser.LR.Instance;
      Algorithm      : in     WisiToken.Parser_Algorithm_Type;
      Semantic_State : in     WisiToken.Token.Semantic_State_Access)
   is
      use WisiToken.Parser.LR;
      use all type WisiToken.Parser_Algorithm_Type;
      Table : constant Parse_Table_Ptr := new Parse_Table
        (State_First       => 0,
         State_Last        => 144,
         First_Terminal    => Descriptor.First_Terminal,
         Last_Terminal     => Descriptor.Last_Terminal,
         First_Nonterminal => Descriptor.First_Nonterminal,
         Last_Nonterminal  => Descriptor.Last_Nonterminal);
      pragma Unreferenced (Algorithm);
   begin
      Table.McKenzie_Param :=
        (First_Terminal    => 3,
         Last_Terminal     => 37,
         First_Nonterminal => 38,
         Last_Nonterminal  => 71,
         Insert =>
           (4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4),
         Delete =>
           (4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 8, 8, 8, 8, 8,
            8, 8, 8, 8, 8, 8, 8, 8,
            8, 8, 8, 8, 8, 8, 8, 8,
            8, 8, 8, 8, 8, 8, 8, 8,
            8, 8, 8, 8, 8),
         Cost_Limit  => 12,
         Check_Limit => 3,
         Patterns    => WisiToken.Parser.LR.Patterns.Empty_List);

      Table.Follow :=
        (39 =>
           (20 |
             26 |
             29 |
             33 => True,
             others => False),
         40 =>
           (5 |
             7 |
             11 |
             15 |
             17 |
             22 |
             24 |
             35 => True,
             others => False),
         41 =>
           (32 => True,
             others => False),
         42 =>
           (20 |
             26 |
             29 |
             33 => True,
             others => False),
         43 =>
           (5 |
             7 |
             11 |
             15 |
             17 |
             22 |
             24 |
             35 => True,
             others => False),
         44 =>
           (7 |
             24 => True,
             others => False),
         45 =>
           (7 |
             24 => True,
             others => False),
         46 =>
           (37 => True,
             others => False),
         47 =>
           (3 |
             4 |
             6 |
             14 |
             21 |
             25 |
             37 => True,
             others => False),
         48 =>
           (3 |
             4 |
             6 |
             14 |
             21 |
             37 => True,
             others => False),
         49 =>
           (5 |
             7 |
             11 |
             15 |
             17 |
             22 |
             24 |
             35 => True,
             others => False),
         50 =>
           (5 |
             7 |
             11 |
             15 |
             17 |
             22 |
             24 |
             35 => True,
             others => False),
         51 =>
           (7 |
             24 => True,
             others => False),
         52 =>
           (20 |
             31 |
             34 => True,
             others => False),
         53 =>
           (31 |
             34 => True,
             others => False),
         54 =>
           (20 |
             26 |
             29 |
             33 => True,
             others => False),
         55 =>
           (20 |
             26 |
             29 |
             33 => True,
             others => False),
         56 =>
           (8 |
             12 |
             19 |
             20 |
             26 |
             29 |
             30 |
             32 |
             33 => True,
             others => False),
         57 =>
           (12 |
             20 |
             26 |
             29 |
             30 |
             32 |
             33 => True,
             others => False),
         58 =>
           (5 |
             7 |
             11 |
             15 |
             17 |
             22 |
             24 |
             35 => True,
             others => False),
         59 =>
           (5 |
             7 |
             11 |
             15 |
             17 |
             22 |
             24 |
             35 => True,
             others => False),
         60 =>
           (5 |
             7 |
             11 |
             15 |
             17 |
             22 |
             24 |
             35 => True,
             others => False),
         61 =>
           (5 |
             7 |
             11 |
             15 |
             17 |
             22 |
             24 |
             35 => True,
             others => False),
         62 =>
           (37 => True,
             others => False),
         63 =>
           (37 => True,
             others => False),
         64 =>
           (18 |
             37 => True,
             others => False),
         65 =>
           (5 |
             7 |
             11 |
             15 |
             17 |
             22 |
             24 |
             35 => True,
             others => False),
         66 =>
           (37 => True,
             others => False),
         67 =>
           (20 |
             26 |
             29 |
             33 => True,
             others => False),
         68 =>
           (20 |
             29 |
             33 => True,
             others => False),
         69 =>
           (20 |
             26 |
             29 |
             33 => True,
             others => False),
         70 =>
           (5 |
             7 |
             11 |
             15 |
             17 |
             22 |
             24 |
             35 => True,
             others => False),
         71 =>
           (3 |
             4 |
             6 |
             14 |
             21 |
             25 |
             37 => True,
             others => False),
         others => (others => False));

      Add_Action (Table.States (0), 3, Reduce, 48, 0,  0, null);
      Add_Action (Table.States (0), 4, Reduce, 48, 0,  0, null);
      Add_Action (Table.States (0), 6, Reduce, 48, 0,  0, null);
      Add_Action (Table.States (0), 14, Reduce, 48, 0,  0, null);
      Add_Action (Table.States (0), 18, Reduce, 48, 0,  0, null);
      Add_Action (Table.States (0), 21, Reduce, 48, 0,  0, null);
      Add_Action (Table.States (0), 25, 7);
      Add_Action (Table.States (0), 37, Reduce, 48, 0,  0, null);
      Add_Error (Table.States (0));
      Add_Goto (Table.States (0), 46, 8);
      Add_Goto (Table.States (0), 47, 9);
      Add_Goto (Table.States (0), 48, 10);
      Add_Goto (Table.States (0), 63, 11);
      Add_Goto (Table.States (0), 66, 12);
      Add_Goto (Table.States (0), 71, 13);
      Add_Action (Table.States (1), 18, Reduce, 64, 1,  1, null);
      Add_Action (Table.States (1), 37, Reduce, 64, 1,  1, null);
      Add_Error (Table.States (1));
      Add_Action (Table.States (2), 14, 33);
      Add_Action (Table.States (2), 18, Reduce, 64, 3,  1, null);
      Add_Action (Table.States (2), 37, Reduce, 64, 3,  1, null);
      Add_Error (Table.States (2));
      Add_Action (Table.States (3), 18, Reduce, 64, 6,  1, null);
      Add_Action (Table.States (3), 37, Reduce, 64, 6,  1, null);
      Add_Error (Table.States (3));
      Add_Action (Table.States (4), 18, Reduce, 64, 5,  1, null);
      Add_Action (Table.States (4), 37, Reduce, 64, 5,  1, null);
      Add_Error (Table.States (4));
      Add_Action (Table.States (5), 8, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (5), 12, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (5), 35, 20);
      Add_Error (Table.States (5));
      Add_Goto (Table.States (5), 56, 32);
      Add_Action (Table.States (6), 18, Reduce, 64, 2,  1, null);
      Add_Action (Table.States (6), 37, Reduce, 64, 2,  1, null);
      Add_Error (Table.States (6));
      Add_Action (Table.States (7), 9, 16);
      Add_Action (Table.States (7), 10, 17);
      Add_Action (Table.States (7), 13, 18);
      Add_Action (Table.States (7), 18, 19);
      Add_Action (Table.States (7), 26, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (7), 29, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (7), 30, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (7), 32, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (7), 33, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (7), 35, 20);
      Add_Action (Table.States (7), 36, 21);
      Add_Error (Table.States (7));
      Add_Goto (Table.States (7), 39, 22);
      Add_Goto (Table.States (7), 41, 23);
      Add_Goto (Table.States (7), 42, 24);
      Add_Goto (Table.States (7), 54, 25);
      Add_Goto (Table.States (7), 55, 26);
      Add_Goto (Table.States (7), 56, 27);
      Add_Goto (Table.States (7), 57, 28);
      Add_Goto (Table.States (7), 67, 29);
      Add_Goto (Table.States (7), 68, 30);
      Add_Goto (Table.States (7), 69, 31);
      Add_Action (Table.States (8), 37, Accept_It, 38, 0,  1, null);
      Add_Error (Table.States (8));
      Add_Action (Table.States (9), 3, Reduce, 48, 1,  1, null);
      Add_Action (Table.States (9), 4, Reduce, 48, 1,  1, null);
      Add_Action (Table.States (9), 6, Reduce, 48, 1,  1, null);
      Add_Action (Table.States (9), 14, Reduce, 48, 1,  1, null);
      Add_Action (Table.States (9), 18, Reduce, 48, 1,  1, null);
      Add_Action (Table.States (9), 21, Reduce, 48, 1,  1, null);
      Add_Action (Table.States (9), 25, 7);
      Add_Action (Table.States (9), 37, Reduce, 48, 1,  1, null);
      Add_Error (Table.States (9));
      Add_Goto (Table.States (9), 71, 15);
      Add_Action (Table.States (10), 3, 1);
      Add_Action (Table.States (10), 4, 2);
      Add_Action (Table.States (10), 6, 3);
      Add_Action (Table.States (10), 14, 4);
      Add_Action (Table.States (10), 18, Reduce, 64, 0,  0, null);
      Add_Action (Table.States (10), 21, 6);
      Add_Action (Table.States (10), 37, Reduce, 64, 0,  0, null);
      Add_Error (Table.States (10));
      Add_Goto (Table.States (10), 64, 14);
      Add_Action (Table.States (11), 37, Reduce, 62, 2,  1, null);
      Add_Error (Table.States (11));
      Add_Action (Table.States (12), 37, Reduce, 62, 1,  1, null);
      Add_Error (Table.States (12));
      Add_Action (Table.States (13), 3, Reduce, 47, 0,  1, null);
      Add_Action (Table.States (13), 4, Reduce, 47, 0,  1, null);
      Add_Action (Table.States (13), 6, Reduce, 47, 0,  1, null);
      Add_Action (Table.States (13), 14, Reduce, 47, 0,  1, null);
      Add_Action (Table.States (13), 18, Reduce, 47, 0,  1, null);
      Add_Action (Table.States (13), 21, Reduce, 47, 0,  1, null);
      Add_Action (Table.States (13), 25, Reduce, 47, 0,  1, null);
      Add_Action (Table.States (13), 37, Reduce, 47, 0,  1, null);
      Add_Error (Table.States (13));
      Add_Action (Table.States (14), 18, 5);
      Add_Action (Table.States (14), 37, Reduce, 62, 0,  0, null);
      Add_Error (Table.States (14));
      Add_Goto (Table.States (14), 62, 46);
      Add_Goto (Table.States (14), 63, 11);
      Add_Goto (Table.States (14), 66, 12);
      Add_Action (Table.States (15), 3, Reduce, 47, 1,  2, null);
      Add_Action (Table.States (15), 4, Reduce, 47, 1,  2, null);
      Add_Action (Table.States (15), 6, Reduce, 47, 1,  2, null);
      Add_Action (Table.States (15), 14, Reduce, 47, 1,  2, null);
      Add_Action (Table.States (15), 18, Reduce, 47, 1,  2, null);
      Add_Action (Table.States (15), 21, Reduce, 47, 1,  2, null);
      Add_Action (Table.States (15), 25, Reduce, 47, 1,  2, null);
      Add_Action (Table.States (15), 37, Reduce, 47, 1,  2, null);
      Add_Error (Table.States (15));
      Add_Action (Table.States (16), 13, 43);
      Add_Error (Table.States (16));
      Add_Goto (Table.States (16), 39, 45);
      Add_Action (Table.States (17), 13, 43);
      Add_Error (Table.States (17));
      Add_Goto (Table.States (17), 39, 44);
      Add_Action (Table.States (18), 9, 16);
      Add_Action (Table.States (18), 10, 17);
      Add_Action (Table.States (18), 13, 18);
      Add_Action (Table.States (18), 18, 19);
      Add_Action (Table.States (18), 20, 41, 56, 0,  0, null);
      Add_Action (Table.States (18), 26, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (18), 29, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (18), 30, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (18), 32, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (18), 35, 20);
      Add_Action (Table.States (18), 36, 21);
      Add_Error (Table.States (18));
      Add_Goto (Table.States (18), 39, 22);
      Add_Goto (Table.States (18), 41, 23);
      Add_Goto (Table.States (18), 42, 24);
      Add_Goto (Table.States (18), 54, 25);
      Add_Goto (Table.States (18), 55, 26);
      Add_Goto (Table.States (18), 56, 27);
      Add_Goto (Table.States (18), 57, 28);
      Add_Goto (Table.States (18), 67, 29);
      Add_Goto (Table.States (18), 68, 42);
      Add_Goto (Table.States (18), 69, 31);
      Add_Action (Table.States (19), 32, Reduce, 41, 0,  1, null);
      Add_Error (Table.States (19));
      Add_Action (Table.States (20), 8, Reduce, 56, 1,  1, null);
      Add_Action (Table.States (20), 12, Reduce, 56, 1,  1, null);
      Add_Action (Table.States (20), 19, Reduce, 56, 1,  1, null);
      Add_Action (Table.States (20), 20, Reduce, 56, 1,  1, null);
      Add_Action (Table.States (20), 26, Reduce, 56, 1,  1, null);
      Add_Action (Table.States (20), 29, Reduce, 56, 1,  1, null);
      Add_Action (Table.States (20), 30, Reduce, 56, 1,  1, null);
      Add_Action (Table.States (20), 32, Reduce, 56, 1,  1, null);
      Add_Action (Table.States (20), 33, Reduce, 56, 1,  1, null);
      Add_Error (Table.States (20));
      Add_Action (Table.States (21), 20, Reduce, 67, 0,  1, null);
      Add_Action (Table.States (21), 26, Reduce, 67, 0,  1, null);
      Add_Action (Table.States (21), 29, Reduce, 67, 0,  1, null);
      Add_Action (Table.States (21), 33, Reduce, 67, 0,  1, null);
      Add_Error (Table.States (21));
      Add_Action (Table.States (22), 20, Reduce, 69, 2,  1, null);
      Add_Action (Table.States (22), 26, Reduce, 69, 2,  1, null);
      Add_Action (Table.States (22), 29, Reduce, 69, 2,  1, null);
      Add_Action (Table.States (22), 33, Reduce, 69, 2,  1, null);
      Add_Error (Table.States (22));
      Add_Action (Table.States (23), 32, 40);
      Add_Error (Table.States (23));
      Add_Action (Table.States (24), 20, Reduce, 67, 3,  1, null);
      Add_Action (Table.States (24), 26, Reduce, 67, 3,  1, null);
      Add_Action (Table.States (24), 29, Reduce, 67, 3,  1, null);
      Add_Action (Table.States (24), 33, Reduce, 67, 3,  1, null);
      Add_Error (Table.States (24));
      Add_Action (Table.States (25), 20, Reduce, 68, 0,  1, null);
      Add_Action (Table.States (25), 26, 39);
      Add_Action (Table.States (25), 29, Reduce, 68, 0,  1, null);
      Add_Action (Table.States (25), 33, Reduce, 68, 0,  1, null);
      Add_Error (Table.States (25));
      Add_Action (Table.States (26), 20, Reduce, 67, 2,  1, null);
      Add_Action (Table.States (26), 26, Reduce, 67, 2,  1, null);
      Add_Action (Table.States (26), 29, Reduce, 67, 2,  1, null);
      Add_Action (Table.States (26), 33, Reduce, 67, 2,  1, null);
      Add_Error (Table.States (26));
      Add_Action (Table.States (27), 12, Reduce, 57, 0,  1, null);
      Add_Action (Table.States (27), 20, Reduce, 57, 0,  1, null);
      Add_Action (Table.States (27), 26, Reduce, 57, 0,  1, null);
      Add_Action (Table.States (27), 29, Reduce, 57, 0,  1, null);
      Add_Action (Table.States (27), 30, Reduce, 57, 0,  1, null);
      Add_Action (Table.States (27), 32, Reduce, 57, 0,  1, null);
      Add_Action (Table.States (27), 33, Reduce, 57, 0,  1, null);
      Add_Error (Table.States (27));
      Add_Action (Table.States (28), 20, Reduce, 67, 1,  1, null);
      Add_Action (Table.States (28), 26, Reduce, 67, 1,  1, null);
      Add_Action (Table.States (28), 29, Reduce, 67, 1,  1, null);
      Add_Action (Table.States (28), 30, 38);
      Add_Action (Table.States (28), 32, Reduce, 41, 1,  1, null);
      Add_Action (Table.States (28), 33, Reduce, 67, 1,  1, null);
      Add_Error (Table.States (28));
      Add_Action (Table.States (29), 20, Reduce, 69, 0,  1, null);
      Add_Action (Table.States (29), 26, Reduce, 69, 0,  1, null);
      Add_Action (Table.States (29), 29, Reduce, 69, 0,  1, null);
      Add_Action (Table.States (29), 33, Reduce, 69, 0,  1, null);
      Add_Error (Table.States (29));
      Add_Action (Table.States (30), 29, 36);
      Add_Action (Table.States (30), 33, 37);
      Add_Error (Table.States (30));
      Add_Action (Table.States (31), 20, Reduce, 54, 0,  1, null);
      Add_Action (Table.States (31), 26, Reduce, 54, 0,  1, null);
      Add_Action (Table.States (31), 29, Reduce, 54, 0,  1, null);
      Add_Action (Table.States (31), 33, Reduce, 54, 0,  1, null);
      Add_Error (Table.States (31));
      Add_Action (Table.States (32), 8, 34);
      Add_Action (Table.States (32), 12, 35);
      Add_Error (Table.States (32));
      Add_Action (Table.States (33), 18, Reduce, 64, 4,  2, null);
      Add_Action (Table.States (33), 37, Reduce, 64, 4,  2, null);
      Add_Error (Table.States (33));
      Add_Action (Table.States (34), 36, 69);
      Add_Error (Table.States (34));
      Add_Action (Table.States (35), 5, 52);
      Add_Action (Table.States (35), 7, Reduce, 51, 0,  0, null);
      Add_Action (Table.States (35), 11, 53);
      Add_Action (Table.States (35), 15, 54);
      Add_Action (Table.States (35), 17, 55);
      Add_Action (Table.States (35), 22, 56);
      Add_Action (Table.States (35), 35, 57);
      Add_Error (Table.States (35));
      Add_Goto (Table.States (35), 40, 58);
      Add_Goto (Table.States (35), 43, 59);
      Add_Goto (Table.States (35), 49, 60);
      Add_Goto (Table.States (35), 50, 61);
      Add_Goto (Table.States (35), 51, 62);
      Add_Goto (Table.States (35), 58, 63);
      Add_Goto (Table.States (35), 59, 64);
      Add_Goto (Table.States (35), 60, 65);
      Add_Goto (Table.States (35), 61, 66);
      Add_Goto (Table.States (35), 65, 67);
      Add_Goto (Table.States (35), 70, 68);
      Add_Action (Table.States (36), 9, 16);
      Add_Action (Table.States (36), 10, 17);
      Add_Action (Table.States (36), 13, 18);
      Add_Action (Table.States (36), 18, 19);
      Add_Action (Table.States (36), 20, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (36), 26, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (36), 29, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (36), 30, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (36), 32, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (36), 33, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (36), 35, 20);
      Add_Action (Table.States (36), 36, 21);
      Add_Error (Table.States (36));
      Add_Goto (Table.States (36), 39, 22);
      Add_Goto (Table.States (36), 41, 23);
      Add_Goto (Table.States (36), 42, 24);
      Add_Goto (Table.States (36), 54, 51);
      Add_Goto (Table.States (36), 55, 26);
      Add_Goto (Table.States (36), 56, 27);
      Add_Goto (Table.States (36), 57, 28);
      Add_Goto (Table.States (36), 67, 29);
      Add_Goto (Table.States (36), 69, 31);
      Add_Action (Table.States (37), 3, Reduce, 71, 0,  3, null);
      Add_Action (Table.States (37), 4, Reduce, 71, 0,  3, null);
      Add_Action (Table.States (37), 6, Reduce, 71, 0,  3, null);
      Add_Action (Table.States (37), 14, Reduce, 71, 0,  3, null);
      Add_Action (Table.States (37), 18, Reduce, 71, 0,  3, null);
      Add_Action (Table.States (37), 21, Reduce, 71, 0,  3, null);
      Add_Action (Table.States (37), 25, Reduce, 71, 0,  3, null);
      Add_Action (Table.States (37), 37, Reduce, 71, 0,  3, null);
      Add_Error (Table.States (37));
      Add_Action (Table.States (38), 35, 50);
      Add_Error (Table.States (38));
      Add_Action (Table.States (39), 9, 16);
      Add_Action (Table.States (39), 10, 17);
      Add_Action (Table.States (39), 13, 18);
      Add_Action (Table.States (39), 18, 19);
      Add_Action (Table.States (39), 20, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (39), 26, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (39), 29, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (39), 30, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (39), 32, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (39), 33, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (39), 35, 20);
      Add_Action (Table.States (39), 36, 21);
      Add_Error (Table.States (39));
      Add_Goto (Table.States (39), 39, 22);
      Add_Goto (Table.States (39), 41, 23);
      Add_Goto (Table.States (39), 42, 24);
      Add_Goto (Table.States (39), 55, 26);
      Add_Goto (Table.States (39), 56, 27);
      Add_Goto (Table.States (39), 57, 28);
      Add_Goto (Table.States (39), 67, 29);
      Add_Goto (Table.States (39), 69, 49);
      Add_Action (Table.States (40), 35, 48);
      Add_Error (Table.States (40));
      Add_Action (Table.States (41), 20, Reduce, 69, 1,  2, null);
      Add_Action (Table.States (41), 26, Reduce, 69, 1,  2, null);
      Add_Action (Table.States (41), 29, Reduce, 69, 1,  2, null);
      Add_Action (Table.States (41), 33, Reduce, 69, 1,  2, null);
      Add_Error (Table.States (41));
      Add_Action (Table.States (42), 20, 47);
      Add_Action (Table.States (42), 29, 36);
      Add_Error (Table.States (42));
      Add_Action (Table.States (43), 9, 16);
      Add_Action (Table.States (43), 10, 17);
      Add_Action (Table.States (43), 13, 18);
      Add_Action (Table.States (43), 18, 19);
      Add_Action (Table.States (43), 20, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (43), 26, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (43), 29, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (43), 30, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (43), 32, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (43), 35, 20);
      Add_Action (Table.States (43), 36, 21);
      Add_Error (Table.States (43));
      Add_Goto (Table.States (43), 39, 22);
      Add_Goto (Table.States (43), 41, 23);
      Add_Goto (Table.States (43), 42, 24);
      Add_Goto (Table.States (43), 54, 25);
      Add_Goto (Table.States (43), 55, 26);
      Add_Goto (Table.States (43), 56, 27);
      Add_Goto (Table.States (43), 57, 28);
      Add_Goto (Table.States (43), 67, 29);
      Add_Goto (Table.States (43), 68, 42);
      Add_Goto (Table.States (43), 69, 31);
      Add_Action (Table.States (44), 20, Reduce, 55, 1,  2, null);
      Add_Action (Table.States (44), 26, Reduce, 55, 1,  2, null);
      Add_Action (Table.States (44), 29, Reduce, 55, 1,  2, null);
      Add_Action (Table.States (44), 33, Reduce, 55, 1,  2, null);
      Add_Error (Table.States (44));
      Add_Action (Table.States (45), 20, Reduce, 55, 0,  2, null);
      Add_Action (Table.States (45), 26, Reduce, 55, 0,  2, null);
      Add_Action (Table.States (45), 29, Reduce, 55, 0,  2, null);
      Add_Action (Table.States (45), 33, Reduce, 55, 0,  2, null);
      Add_Error (Table.States (45));
      Add_Action (Table.States (46), 37, Reduce, 46, 0,  3, null);
      Add_Error (Table.States (46));
      Add_Action (Table.States (47), 20, Reduce, 39, 0,  3, aggregate_g_0'Access);
      Add_Action (Table.States (47), 26, Reduce, 39, 0,  3, aggregate_g_0'Access);
      Add_Action (Table.States (47), 29, Reduce, 39, 0,  3, aggregate_g_0'Access);
      Add_Action (Table.States (47), 33, Reduce, 39, 0,  3, aggregate_g_0'Access);
      Add_Error (Table.States (47));
      Add_Action (Table.States (48), 13, 81);
      Add_Action (Table.States (48), 20, Reduce, 42, 0,  3, null);
      Add_Action (Table.States (48), 26, Reduce, 42, 0,  3, null);
      Add_Action (Table.States (48), 29, Reduce, 42, 0,  3, null);
      Add_Action (Table.States (48), 33, Reduce, 42, 0,  3, null);
      Add_Error (Table.States (48));
      Add_Action (Table.States (49), 20, Reduce, 54, 1,  3, null);
      Add_Action (Table.States (49), 26, Reduce, 54, 1,  3, null);
      Add_Action (Table.States (49), 29, Reduce, 54, 1,  3, null);
      Add_Action (Table.States (49), 33, Reduce, 54, 1,  3, null);
      Add_Error (Table.States (49));
      Add_Action (Table.States (50), 12, Reduce, 57, 1,  3, null);
      Add_Action (Table.States (50), 20, Reduce, 57, 1,  3, null);
      Add_Action (Table.States (50), 26, Reduce, 57, 1,  3, null);
      Add_Action (Table.States (50), 29, Reduce, 57, 1,  3, null);
      Add_Action (Table.States (50), 30, Reduce, 57, 1,  3, null);
      Add_Action (Table.States (50), 32, Reduce, 57, 1,  3, null);
      Add_Action (Table.States (50), 33, Reduce, 57, 1,  3, null);
      Add_Error (Table.States (50));
      Add_Action (Table.States (51), 20, Reduce, 68, 1,  3, null);
      Add_Action (Table.States (51), 26, 39);
      Add_Action (Table.States (51), 29, Reduce, 68, 1,  3, null);
      Add_Action (Table.States (51), 33, Reduce, 68, 1,  3, null);
      Add_Error (Table.States (51));
      Add_Action (Table.States (52), 12, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (52), 30, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (52), 35, 20);
      Add_Error (Table.States (52));
      Add_Goto (Table.States (52), 56, 27);
      Add_Goto (Table.States (52), 57, 80);
      Add_Action (Table.States (53), 9, 78);
      Add_Action (Table.States (53), 35, 79);
      Add_Error (Table.States (53));
      Add_Action (Table.States (54), 33, 77);
      Add_Error (Table.States (54));
      Add_Action (Table.States (55), 8, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (55), 12, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (55), 19, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (55), 35, 20);
      Add_Error (Table.States (55));
      Add_Goto (Table.States (55), 56, 76);
      Add_Action (Table.States (56), 35, 75);
      Add_Error (Table.States (56));
      Add_Action (Table.States (57), 27, 73);
      Add_Action (Table.States (57), 28, 74);
      Add_Error (Table.States (57));
      Add_Action (Table.States (58), 5, Reduce, 65, 2,  1, null);
      Add_Action (Table.States (58), 7, Reduce, 65, 2,  1, null);
      Add_Action (Table.States (58), 11, Reduce, 65, 2,  1, null);
      Add_Action (Table.States (58), 15, Reduce, 65, 2,  1, null);
      Add_Action (Table.States (58), 17, Reduce, 65, 2,  1, null);
      Add_Action (Table.States (58), 22, Reduce, 65, 2,  1, null);
      Add_Action (Table.States (58), 24, Reduce, 65, 2,  1, null);
      Add_Action (Table.States (58), 35, Reduce, 65, 2,  1, null);
      Add_Error (Table.States (58));
      Add_Action (Table.States (59), 5, Reduce, 65, 3,  1, null);
      Add_Action (Table.States (59), 7, Reduce, 65, 3,  1, null);
      Add_Action (Table.States (59), 11, Reduce, 65, 3,  1, null);
      Add_Action (Table.States (59), 15, Reduce, 65, 3,  1, null);
      Add_Action (Table.States (59), 17, Reduce, 65, 3,  1, null);
      Add_Action (Table.States (59), 22, Reduce, 65, 3,  1, null);
      Add_Action (Table.States (59), 24, Reduce, 65, 3,  1, null);
      Add_Action (Table.States (59), 35, Reduce, 65, 3,  1, null);
      Add_Error (Table.States (59));
      Add_Action (Table.States (60), 5, Reduce, 50, 0,  1, null);
      Add_Action (Table.States (60), 7, Reduce, 50, 0,  1, null);
      Add_Action (Table.States (60), 11, Reduce, 50, 0,  1, null);
      Add_Action (Table.States (60), 15, Reduce, 50, 0,  1, null);
      Add_Action (Table.States (60), 17, Reduce, 50, 0,  1, null);
      Add_Action (Table.States (60), 22, Reduce, 50, 0,  1, null);
      Add_Action (Table.States (60), 24, Reduce, 50, 0,  1, null);
      Add_Action (Table.States (60), 35, Reduce, 50, 0,  1, null);
      Add_Error (Table.States (60));
      Add_Action (Table.States (61), 5, 52);
      Add_Action (Table.States (61), 7, Reduce, 51, 1,  1, null);
      Add_Action (Table.States (61), 11, 53);
      Add_Action (Table.States (61), 15, 54);
      Add_Action (Table.States (61), 17, 55);
      Add_Action (Table.States (61), 22, 56);
      Add_Action (Table.States (61), 24, Reduce, 51, 1,  1, null);
      Add_Action (Table.States (61), 35, 57);
      Add_Error (Table.States (61));
      Add_Goto (Table.States (61), 40, 58);
      Add_Goto (Table.States (61), 43, 59);
      Add_Goto (Table.States (61), 49, 72);
      Add_Goto (Table.States (61), 58, 63);
      Add_Goto (Table.States (61), 59, 64);
      Add_Goto (Table.States (61), 60, 65);
      Add_Goto (Table.States (61), 61, 66);
      Add_Goto (Table.States (61), 65, 67);
      Add_Goto (Table.States (61), 70, 68);
      Add_Action (Table.States (62), 7, 71);
      Add_Error (Table.States (62));
      Add_Action (Table.States (63), 5, Reduce, 49, 2,  1, null);
      Add_Action (Table.States (63), 7, Reduce, 49, 2,  1, null);
      Add_Action (Table.States (63), 11, Reduce, 49, 2,  1, null);
      Add_Action (Table.States (63), 15, Reduce, 49, 2,  1, null);
      Add_Action (Table.States (63), 17, Reduce, 49, 2,  1, null);
      Add_Action (Table.States (63), 22, Reduce, 49, 2,  1, null);
      Add_Action (Table.States (63), 24, Reduce, 49, 2,  1, null);
      Add_Action (Table.States (63), 35, Reduce, 49, 2,  1, null);
      Add_Error (Table.States (63));
      Add_Action (Table.States (64), 5, Reduce, 58, 0,  1, null);
      Add_Action (Table.States (64), 7, Reduce, 58, 0,  1, null);
      Add_Action (Table.States (64), 11, Reduce, 58, 0,  1, null);
      Add_Action (Table.States (64), 15, Reduce, 58, 0,  1, null);
      Add_Action (Table.States (64), 17, Reduce, 58, 0,  1, null);
      Add_Action (Table.States (64), 22, Reduce, 58, 0,  1, null);
      Add_Action (Table.States (64), 24, Reduce, 58, 0,  1, null);
      Add_Action (Table.States (64), 35, Reduce, 58, 0,  1, null);
      Add_Error (Table.States (64));
      Add_Action (Table.States (65), 5, Reduce, 58, 1,  1, null);
      Add_Action (Table.States (65), 7, Reduce, 58, 1,  1, null);
      Add_Action (Table.States (65), 11, Reduce, 58, 1,  1, null);
      Add_Action (Table.States (65), 15, Reduce, 58, 1,  1, null);
      Add_Action (Table.States (65), 17, Reduce, 58, 1,  1, null);
      Add_Action (Table.States (65), 22, Reduce, 58, 1,  1, null);
      Add_Action (Table.States (65), 24, Reduce, 58, 1,  1, null);
      Add_Action (Table.States (65), 35, Reduce, 58, 1,  1, null);
      Add_Error (Table.States (65));
      Add_Action (Table.States (66), 5, Reduce, 58, 2,  1, null);
      Add_Action (Table.States (66), 7, Reduce, 58, 2,  1, null);
      Add_Action (Table.States (66), 11, Reduce, 58, 2,  1, null);
      Add_Action (Table.States (66), 15, Reduce, 58, 2,  1, null);
      Add_Action (Table.States (66), 17, Reduce, 58, 2,  1, null);
      Add_Action (Table.States (66), 22, Reduce, 58, 2,  1, null);
      Add_Action (Table.States (66), 24, Reduce, 58, 2,  1, null);
      Add_Action (Table.States (66), 35, Reduce, 58, 2,  1, null);
      Add_Error (Table.States (66));
      Add_Action (Table.States (67), 5, Reduce, 49, 0,  1, null);
      Add_Action (Table.States (67), 7, Reduce, 49, 0,  1, null);
      Add_Action (Table.States (67), 11, Reduce, 49, 0,  1, null);
      Add_Action (Table.States (67), 15, Reduce, 49, 0,  1, null);
      Add_Action (Table.States (67), 17, Reduce, 49, 0,  1, null);
      Add_Action (Table.States (67), 22, Reduce, 49, 0,  1, null);
      Add_Action (Table.States (67), 24, Reduce, 49, 0,  1, null);
      Add_Action (Table.States (67), 35, Reduce, 49, 0,  1, null);
      Add_Error (Table.States (67));
      Add_Action (Table.States (68), 5, Reduce, 49, 1,  1, null);
      Add_Action (Table.States (68), 7, Reduce, 49, 1,  1, null);
      Add_Action (Table.States (68), 11, Reduce, 49, 1,  1, null);
      Add_Action (Table.States (68), 15, Reduce, 49, 1,  1, null);
      Add_Action (Table.States (68), 17, Reduce, 49, 1,  1, null);
      Add_Action (Table.States (68), 22, Reduce, 49, 1,  1, null);
      Add_Action (Table.States (68), 24, Reduce, 49, 1,  1, null);
      Add_Action (Table.States (68), 35, Reduce, 49, 1,  1, null);
      Add_Error (Table.States (68));
      Add_Action (Table.States (69), 12, 70);
      Add_Error (Table.States (69));
      Add_Action (Table.States (70), 5, 52);
      Add_Action (Table.States (70), 7, Reduce, 51, 0,  0, null);
      Add_Action (Table.States (70), 11, 53);
      Add_Action (Table.States (70), 15, 54);
      Add_Action (Table.States (70), 17, 55);
      Add_Action (Table.States (70), 22, 56);
      Add_Action (Table.States (70), 35, 57);
      Add_Error (Table.States (70));
      Add_Goto (Table.States (70), 40, 58);
      Add_Goto (Table.States (70), 43, 59);
      Add_Goto (Table.States (70), 49, 60);
      Add_Goto (Table.States (70), 50, 61);
      Add_Goto (Table.States (70), 51, 94);
      Add_Goto (Table.States (70), 58, 63);
      Add_Goto (Table.States (70), 59, 64);
      Add_Goto (Table.States (70), 60, 65);
      Add_Goto (Table.States (70), 61, 66);
      Add_Goto (Table.States (70), 65, 67);
      Add_Goto (Table.States (70), 70, 68);
      Add_Action (Table.States (71), 33, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (71), 35, 20);
      Add_Error (Table.States (71));
      Add_Goto (Table.States (71), 56, 93);
      Add_Action (Table.States (72), 5, Reduce, 50, 1,  2, null);
      Add_Action (Table.States (72), 7, Reduce, 50, 1,  2, null);
      Add_Action (Table.States (72), 11, Reduce, 50, 1,  2, null);
      Add_Action (Table.States (72), 15, Reduce, 50, 1,  2, null);
      Add_Action (Table.States (72), 17, Reduce, 50, 1,  2, null);
      Add_Action (Table.States (72), 22, Reduce, 50, 1,  2, null);
      Add_Action (Table.States (72), 24, Reduce, 50, 1,  2, null);
      Add_Action (Table.States (72), 35, Reduce, 50, 1,  2, null);
      Add_Error (Table.States (72));
      Add_Action (Table.States (73), 35, 92);
      Add_Error (Table.States (73));
      Add_Action (Table.States (74), 9, 16);
      Add_Action (Table.States (74), 10, 17);
      Add_Action (Table.States (74), 13, 18);
      Add_Action (Table.States (74), 18, 19);
      Add_Action (Table.States (74), 26, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (74), 30, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (74), 32, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (74), 33, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (74), 35, 20);
      Add_Action (Table.States (74), 36, 21);
      Add_Error (Table.States (74));
      Add_Goto (Table.States (74), 39, 22);
      Add_Goto (Table.States (74), 41, 23);
      Add_Goto (Table.States (74), 42, 24);
      Add_Goto (Table.States (74), 54, 91);
      Add_Goto (Table.States (74), 55, 26);
      Add_Goto (Table.States (74), 56, 27);
      Add_Goto (Table.States (74), 57, 28);
      Add_Goto (Table.States (74), 67, 29);
      Add_Goto (Table.States (74), 69, 31);
      Add_Action (Table.States (75), 12, 90);
      Add_Error (Table.States (75));
      Add_Action (Table.States (76), 8, 87);
      Add_Action (Table.States (76), 12, 88);
      Add_Action (Table.States (76), 19, 89);
      Add_Error (Table.States (76));
      Add_Action (Table.States (77), 5, Reduce, 65, 4,  2, simple_declarative_item_4'Access);
      Add_Action (Table.States (77), 7, Reduce, 65, 4,  2, simple_declarative_item_4'Access);
      Add_Action (Table.States (77), 11, Reduce, 65, 4,  2, simple_declarative_item_4'Access);
      Add_Action (Table.States (77), 15, Reduce, 65, 4,  2, simple_declarative_item_4'Access);
      Add_Action (Table.States (77), 17, Reduce, 65, 4,  2, simple_declarative_item_4'Access);
      Add_Action (Table.States (77), 22, Reduce, 65, 4,  2, simple_declarative_item_4'Access);
      Add_Action (Table.States (77), 24, Reduce, 65, 4,  2, simple_declarative_item_4'Access);
      Add_Action (Table.States (77), 35, Reduce, 65, 4,  2, simple_declarative_item_4'Access);
      Add_Error (Table.States (77));
      Add_Action (Table.States (78), 13, 86);
      Add_Error (Table.States (78));
      Add_Action (Table.States (79), 13, 84);
      Add_Action (Table.States (79), 23, 85);
      Add_Error (Table.States (79));
      Add_Action (Table.States (80), 12, 83);
      Add_Action (Table.States (80), 30, 38);
      Add_Error (Table.States (80));
      Add_Action (Table.States (81), 36, 82);
      Add_Error (Table.States (81));
      Add_Action (Table.States (82), 20, 111);
      Add_Error (Table.States (82));
      Add_Action (Table.States (83), 7, Reduce, 45, 0,  0, null);
      Add_Action (Table.States (83), 24, 108, 45, 0,  0, null);
      Add_Error (Table.States (83));
      Add_Goto (Table.States (83), 44, 109);
      Add_Goto (Table.States (83), 45, 110);
      Add_Action (Table.States (84), 16, 105);
      Add_Action (Table.States (84), 20, Reduce, 52, 0,  0, null);
      Add_Action (Table.States (84), 36, 106);
      Add_Error (Table.States (84));
      Add_Goto (Table.States (84), 52, 107);
      Add_Action (Table.States (85), 9, 16);
      Add_Action (Table.States (85), 10, 17);
      Add_Action (Table.States (85), 13, 18);
      Add_Action (Table.States (85), 18, 19);
      Add_Action (Table.States (85), 26, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (85), 30, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (85), 32, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (85), 33, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (85), 35, 20);
      Add_Action (Table.States (85), 36, 21);
      Add_Error (Table.States (85));
      Add_Goto (Table.States (85), 39, 22);
      Add_Goto (Table.States (85), 41, 23);
      Add_Goto (Table.States (85), 42, 24);
      Add_Goto (Table.States (85), 54, 104);
      Add_Goto (Table.States (85), 55, 26);
      Add_Goto (Table.States (85), 56, 27);
      Add_Goto (Table.States (85), 57, 28);
      Add_Goto (Table.States (85), 67, 29);
      Add_Goto (Table.States (85), 69, 31);
      Add_Action (Table.States (86), 36, 103);
      Add_Error (Table.States (86));
      Add_Action (Table.States (87), 12, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (87), 30, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (87), 35, 20);
      Add_Error (Table.States (87));
      Add_Goto (Table.States (87), 56, 27);
      Add_Goto (Table.States (87), 57, 102);
      Add_Action (Table.States (88), 5, 52);
      Add_Action (Table.States (88), 7, Reduce, 51, 0,  0, null);
      Add_Action (Table.States (88), 11, 53);
      Add_Action (Table.States (88), 15, 54);
      Add_Action (Table.States (88), 17, 55);
      Add_Action (Table.States (88), 22, 56);
      Add_Action (Table.States (88), 35, 57);
      Add_Error (Table.States (88));
      Add_Goto (Table.States (88), 40, 58);
      Add_Goto (Table.States (88), 43, 59);
      Add_Goto (Table.States (88), 49, 60);
      Add_Goto (Table.States (88), 50, 61);
      Add_Goto (Table.States (88), 51, 101);
      Add_Goto (Table.States (88), 58, 63);
      Add_Goto (Table.States (88), 59, 64);
      Add_Goto (Table.States (88), 60, 65);
      Add_Goto (Table.States (88), 61, 66);
      Add_Goto (Table.States (88), 65, 67);
      Add_Goto (Table.States (88), 70, 68);
      Add_Action (Table.States (89), 30, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (89), 33, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (89), 35, 20);
      Add_Error (Table.States (89));
      Add_Goto (Table.States (89), 56, 27);
      Add_Goto (Table.States (89), 57, 100);
      Add_Action (Table.States (90), 13, 43);
      Add_Error (Table.States (90));
      Add_Goto (Table.States (90), 39, 99);
      Add_Action (Table.States (91), 26, 39);
      Add_Action (Table.States (91), 33, 98);
      Add_Error (Table.States (91));
      Add_Action (Table.States (92), 28, 97);
      Add_Error (Table.States (92));
      Add_Action (Table.States (93), 33, 96);
      Add_Error (Table.States (93));
      Add_Action (Table.States (94), 7, 95);
      Add_Error (Table.States (94));
      Add_Action (Table.States (95), 33, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (95), 35, 20);
      Add_Error (Table.States (95));
      Add_Goto (Table.States (95), 56, 124);
      Add_Action (Table.States (96), 37, Reduce, 66, 0,  7, simple_project_declaration_0'Access);
      Add_Error (Table.States (96));
      Add_Action (Table.States (97), 9, 16);
      Add_Action (Table.States (97), 10, 17);
      Add_Action (Table.States (97), 13, 18);
      Add_Action (Table.States (97), 18, 19);
      Add_Action (Table.States (97), 26, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (97), 30, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (97), 32, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (97), 33, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (97), 35, 20);
      Add_Action (Table.States (97), 36, 21);
      Add_Error (Table.States (97));
      Add_Goto (Table.States (97), 39, 22);
      Add_Goto (Table.States (97), 41, 23);
      Add_Goto (Table.States (97), 42, 24);
      Add_Goto (Table.States (97), 54, 123);
      Add_Goto (Table.States (97), 55, 26);
      Add_Goto (Table.States (97), 56, 27);
      Add_Goto (Table.States (97), 57, 28);
      Add_Goto (Table.States (97), 67, 29);
      Add_Goto (Table.States (97), 69, 31);
      Add_Action (Table.States (98), 5, Reduce, 65, 0,  4, simple_declarative_item_0'Access);
      Add_Action (Table.States (98), 7, Reduce, 65, 0,  4, simple_declarative_item_0'Access);
      Add_Action (Table.States (98), 11, Reduce, 65, 0,  4, simple_declarative_item_0'Access);
      Add_Action (Table.States (98), 15, Reduce, 65, 0,  4, simple_declarative_item_0'Access);
      Add_Action (Table.States (98), 17, Reduce, 65, 0,  4, simple_declarative_item_0'Access);
      Add_Action (Table.States (98), 22, Reduce, 65, 0,  4, simple_declarative_item_0'Access);
      Add_Action (Table.States (98), 24, Reduce, 65, 0,  4, simple_declarative_item_0'Access);
      Add_Action (Table.States (98), 35, Reduce, 65, 0,  4, simple_declarative_item_0'Access);
      Add_Error (Table.States (98));
      Add_Action (Table.States (99), 33, 122);
      Add_Error (Table.States (99));
      Add_Action (Table.States (100), 30, 38);
      Add_Action (Table.States (100), 33, 121);
      Add_Error (Table.States (100));
      Add_Action (Table.States (101), 7, 120);
      Add_Error (Table.States (101));
      Add_Action (Table.States (102), 12, 119);
      Add_Action (Table.States (102), 30, 38);
      Add_Error (Table.States (102));
      Add_Action (Table.States (103), 20, 118);
      Add_Error (Table.States (103));
      Add_Action (Table.States (104), 26, 39);
      Add_Action (Table.States (104), 33, 117);
      Add_Error (Table.States (104));
      Add_Action (Table.States (105), 20, Reduce, 52, 2,  1, null);
      Add_Action (Table.States (105), 31, Reduce, 52, 2,  1, null);
      Add_Action (Table.States (105), 34, Reduce, 52, 2,  1, null);
      Add_Error (Table.States (105));
      Add_Action (Table.States (106), 20, Reduce, 52, 1,  1, null);
      Add_Action (Table.States (106), 31, Reduce, 52, 1,  1, null);
      Add_Action (Table.States (106), 34, Reduce, 52, 1,  1, null);
      Add_Error (Table.States (106));
      Add_Action (Table.States (107), 20, 116);
      Add_Error (Table.States (107));
      Add_Action (Table.States (108), 16, 105);
      Add_Action (Table.States (108), 31, Reduce, 52, 0,  0, null);
      Add_Action (Table.States (108), 34, Reduce, 52, 0,  0, null);
      Add_Action (Table.States (108), 36, 106);
      Add_Error (Table.States (108));
      Add_Goto (Table.States (108), 52, 114);
      Add_Goto (Table.States (108), 53, 115);
      Add_Action (Table.States (109), 7, Reduce, 45, 1,  1, null);
      Add_Action (Table.States (109), 24, Reduce, 45, 1,  1, null);
      Add_Error (Table.States (109));
      Add_Action (Table.States (110), 7, 112);
      Add_Action (Table.States (110), 24, 108);
      Add_Error (Table.States (110));
      Add_Goto (Table.States (110), 44, 113);
      Add_Action (Table.States (111), 20, Reduce, 42, 1,  6, null);
      Add_Action (Table.States (111), 26, Reduce, 42, 1,  6, null);
      Add_Action (Table.States (111), 29, Reduce, 42, 1,  6, null);
      Add_Action (Table.States (111), 33, Reduce, 42, 1,  6, null);
      Add_Error (Table.States (111));
      Add_Action (Table.States (112), 5, 133);
      Add_Error (Table.States (112));
      Add_Action (Table.States (113), 7, Reduce, 45, 2,  2, null);
      Add_Action (Table.States (113), 24, Reduce, 45, 2,  2, null);
      Add_Error (Table.States (113));
      Add_Action (Table.States (114), 31, Reduce, 53, 0,  1, null);
      Add_Action (Table.States (114), 34, Reduce, 53, 0,  1, null);
      Add_Error (Table.States (114));
      Add_Action (Table.States (115), 31, 131);
      Add_Action (Table.States (115), 34, 132);
      Add_Error (Table.States (115));
      Add_Action (Table.States (116), 23, 130);
      Add_Error (Table.States (116));
      Add_Action (Table.States (117), 5, Reduce, 40, 0,  5, attribute_declaration_0'Access);
      Add_Action (Table.States (117), 7, Reduce, 40, 0,  5, attribute_declaration_0'Access);
      Add_Action (Table.States (117), 11, Reduce, 40, 0,  5, attribute_declaration_0'Access);
      Add_Action (Table.States (117), 15, Reduce, 40, 0,  5, attribute_declaration_0'Access);
      Add_Action (Table.States (117), 17, Reduce, 40, 0,  5, attribute_declaration_0'Access);
      Add_Action (Table.States (117), 22, Reduce, 40, 0,  5, attribute_declaration_0'Access);
      Add_Action (Table.States (117), 24, Reduce, 40, 0,  5, attribute_declaration_0'Access);
      Add_Action (Table.States (117), 35, Reduce, 40, 0,  5, attribute_declaration_0'Access);
      Add_Error (Table.States (117));
      Add_Action (Table.States (118), 23, 129);
      Add_Error (Table.States (118));
      Add_Action (Table.States (119), 5, 52);
      Add_Action (Table.States (119), 7, Reduce, 51, 0,  0, null);
      Add_Action (Table.States (119), 11, 53);
      Add_Action (Table.States (119), 15, 54);
      Add_Action (Table.States (119), 17, 55);
      Add_Action (Table.States (119), 22, 56);
      Add_Action (Table.States (119), 35, 57);
      Add_Error (Table.States (119));
      Add_Goto (Table.States (119), 40, 58);
      Add_Goto (Table.States (119), 43, 59);
      Add_Goto (Table.States (119), 49, 60);
      Add_Goto (Table.States (119), 50, 61);
      Add_Goto (Table.States (119), 51, 128);
      Add_Goto (Table.States (119), 58, 63);
      Add_Goto (Table.States (119), 59, 64);
      Add_Goto (Table.States (119), 60, 65);
      Add_Goto (Table.States (119), 61, 66);
      Add_Goto (Table.States (119), 65, 67);
      Add_Goto (Table.States (119), 70, 68);
      Add_Action (Table.States (120), 33, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (120), 35, 20);
      Add_Error (Table.States (120));
      Add_Goto (Table.States (120), 56, 127);
      Add_Action (Table.States (121), 5, Reduce, 61, 0,  5, package_renaming_0'Access);
      Add_Action (Table.States (121), 7, Reduce, 61, 0,  5, package_renaming_0'Access);
      Add_Action (Table.States (121), 11, Reduce, 61, 0,  5, package_renaming_0'Access);
      Add_Action (Table.States (121), 15, Reduce, 61, 0,  5, package_renaming_0'Access);
      Add_Action (Table.States (121), 17, Reduce, 61, 0,  5, package_renaming_0'Access);
      Add_Action (Table.States (121), 22, Reduce, 61, 0,  5, package_renaming_0'Access);
      Add_Action (Table.States (121), 24, Reduce, 61, 0,  5, package_renaming_0'Access);
      Add_Action (Table.States (121), 35, Reduce, 61, 0,  5, package_renaming_0'Access);
      Add_Error (Table.States (121));
      Add_Action (Table.States (122), 5, Reduce, 70, 0,  5, typed_string_declaration_0'Access);
      Add_Action (Table.States (122), 7, Reduce, 70, 0,  5, typed_string_declaration_0'Access);
      Add_Action (Table.States (122), 11, Reduce, 70, 0,  5, typed_string_declaration_0'Access);
      Add_Action (Table.States (122), 15, Reduce, 70, 0,  5, typed_string_declaration_0'Access);
      Add_Action (Table.States (122), 17, Reduce, 70, 0,  5, typed_string_declaration_0'Access);
      Add_Action (Table.States (122), 22, Reduce, 70, 0,  5, typed_string_declaration_0'Access);
      Add_Action (Table.States (122), 24, Reduce, 70, 0,  5, typed_string_declaration_0'Access);
      Add_Action (Table.States (122), 35, Reduce, 70, 0,  5, typed_string_declaration_0'Access);
      Add_Error (Table.States (122));
      Add_Action (Table.States (123), 26, 39);
      Add_Action (Table.States (123), 33, 126);
      Add_Error (Table.States (123));
      Add_Action (Table.States (124), 33, 125);
      Add_Error (Table.States (124));
      Add_Action (Table.States (125), 37, Reduce, 63, 0,  9, project_extension_0'Access);
      Add_Error (Table.States (125));
      Add_Action (Table.States (126), 5, Reduce, 65, 1,  6, simple_declarative_item_1'Access);
      Add_Action (Table.States (126), 7, Reduce, 65, 1,  6, simple_declarative_item_1'Access);
      Add_Action (Table.States (126), 11, Reduce, 65, 1,  6, simple_declarative_item_1'Access);
      Add_Action (Table.States (126), 15, Reduce, 65, 1,  6, simple_declarative_item_1'Access);
      Add_Action (Table.States (126), 17, Reduce, 65, 1,  6, simple_declarative_item_1'Access);
      Add_Action (Table.States (126), 22, Reduce, 65, 1,  6, simple_declarative_item_1'Access);
      Add_Action (Table.States (126), 24, Reduce, 65, 1,  6, simple_declarative_item_1'Access);
      Add_Action (Table.States (126), 35, Reduce, 65, 1,  6, simple_declarative_item_1'Access);
      Add_Error (Table.States (126));
      Add_Action (Table.States (127), 33, 140);
      Add_Error (Table.States (127));
      Add_Action (Table.States (128), 7, 139);
      Add_Error (Table.States (128));
      Add_Action (Table.States (129), 9, 16);
      Add_Action (Table.States (129), 10, 17);
      Add_Action (Table.States (129), 13, 18);
      Add_Action (Table.States (129), 18, 19);
      Add_Action (Table.States (129), 26, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (129), 30, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (129), 32, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (129), 33, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (129), 35, 20);
      Add_Action (Table.States (129), 36, 21);
      Add_Error (Table.States (129));
      Add_Goto (Table.States (129), 39, 22);
      Add_Goto (Table.States (129), 41, 23);
      Add_Goto (Table.States (129), 42, 24);
      Add_Goto (Table.States (129), 54, 138);
      Add_Goto (Table.States (129), 55, 26);
      Add_Goto (Table.States (129), 56, 27);
      Add_Goto (Table.States (129), 57, 28);
      Add_Goto (Table.States (129), 67, 29);
      Add_Goto (Table.States (129), 69, 31);
      Add_Action (Table.States (130), 9, 16);
      Add_Action (Table.States (130), 10, 17);
      Add_Action (Table.States (130), 13, 18);
      Add_Action (Table.States (130), 18, 19);
      Add_Action (Table.States (130), 26, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (130), 30, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (130), 32, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (130), 33, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (130), 35, 20);
      Add_Action (Table.States (130), 36, 21);
      Add_Error (Table.States (130));
      Add_Goto (Table.States (130), 39, 22);
      Add_Goto (Table.States (130), 41, 23);
      Add_Goto (Table.States (130), 42, 24);
      Add_Goto (Table.States (130), 54, 137);
      Add_Goto (Table.States (130), 55, 26);
      Add_Goto (Table.States (130), 56, 27);
      Add_Goto (Table.States (130), 57, 28);
      Add_Goto (Table.States (130), 67, 29);
      Add_Goto (Table.States (130), 69, 31);
      Add_Action (Table.States (131), 5, 52);
      Add_Action (Table.States (131), 7, Reduce, 51, 0,  0, null);
      Add_Action (Table.States (131), 11, 53);
      Add_Action (Table.States (131), 15, 54);
      Add_Action (Table.States (131), 17, 55);
      Add_Action (Table.States (131), 22, 56);
      Add_Action (Table.States (131), 24, Reduce, 51, 0,  0, null);
      Add_Action (Table.States (131), 35, 57);
      Add_Error (Table.States (131));
      Add_Goto (Table.States (131), 40, 58);
      Add_Goto (Table.States (131), 43, 59);
      Add_Goto (Table.States (131), 49, 60);
      Add_Goto (Table.States (131), 50, 61);
      Add_Goto (Table.States (131), 51, 136);
      Add_Goto (Table.States (131), 58, 63);
      Add_Goto (Table.States (131), 59, 64);
      Add_Goto (Table.States (131), 60, 65);
      Add_Goto (Table.States (131), 61, 66);
      Add_Goto (Table.States (131), 65, 67);
      Add_Goto (Table.States (131), 70, 68);
      Add_Action (Table.States (132), 16, 105);
      Add_Action (Table.States (132), 31, Reduce, 52, 0,  0, null);
      Add_Action (Table.States (132), 34, Reduce, 52, 0,  0, null);
      Add_Action (Table.States (132), 36, 106);
      Add_Error (Table.States (132));
      Add_Goto (Table.States (132), 52, 135);
      Add_Action (Table.States (133), 33, 134);
      Add_Error (Table.States (133));
      Add_Action (Table.States (134), 5, Reduce, 43, 0,  7, case_statement_0'Access);
      Add_Action (Table.States (134), 7, Reduce, 43, 0,  7, case_statement_0'Access);
      Add_Action (Table.States (134), 11, Reduce, 43, 0,  7, case_statement_0'Access);
      Add_Action (Table.States (134), 15, Reduce, 43, 0,  7, case_statement_0'Access);
      Add_Action (Table.States (134), 17, Reduce, 43, 0,  7, case_statement_0'Access);
      Add_Action (Table.States (134), 22, Reduce, 43, 0,  7, case_statement_0'Access);
      Add_Action (Table.States (134), 24, Reduce, 43, 0,  7, case_statement_0'Access);
      Add_Action (Table.States (134), 35, Reduce, 43, 0,  7, case_statement_0'Access);
      Add_Error (Table.States (134));
      Add_Action (Table.States (135), 31, Reduce, 53, 1,  3, null);
      Add_Action (Table.States (135), 34, Reduce, 53, 1,  3, null);
      Add_Error (Table.States (135));
      Add_Action (Table.States (136), 7, Reduce, 44, 0,  4, case_item_0'Access);
      Add_Action (Table.States (136), 24, Reduce, 44, 0,  4, case_item_0'Access);
      Add_Error (Table.States (136));
      Add_Action (Table.States (137), 26, 39);
      Add_Action (Table.States (137), 33, 143);
      Add_Error (Table.States (137));
      Add_Action (Table.States (138), 26, 39);
      Add_Action (Table.States (138), 33, 142);
      Add_Error (Table.States (138));
      Add_Action (Table.States (139), 33, Reduce, 56, 0,  0, null);
      Add_Action (Table.States (139), 35, 20);
      Add_Error (Table.States (139));
      Add_Goto (Table.States (139), 56, 141);
      Add_Action (Table.States (140), 5, Reduce, 59, 0,  7, package_spec_0'Access);
      Add_Action (Table.States (140), 7, Reduce, 59, 0,  7, package_spec_0'Access);
      Add_Action (Table.States (140), 11, Reduce, 59, 0,  7, package_spec_0'Access);
      Add_Action (Table.States (140), 15, Reduce, 59, 0,  7, package_spec_0'Access);
      Add_Action (Table.States (140), 17, Reduce, 59, 0,  7, package_spec_0'Access);
      Add_Action (Table.States (140), 22, Reduce, 59, 0,  7, package_spec_0'Access);
      Add_Action (Table.States (140), 24, Reduce, 59, 0,  7, package_spec_0'Access);
      Add_Action (Table.States (140), 35, Reduce, 59, 0,  7, package_spec_0'Access);
      Add_Error (Table.States (140));
      Add_Action (Table.States (141), 33, 144);
      Add_Error (Table.States (141));
      Add_Action (Table.States (142), 5, Reduce, 40, 2,  8, attribute_declaration_2'Access);
      Add_Action (Table.States (142), 7, Reduce, 40, 2,  8, attribute_declaration_2'Access);
      Add_Action (Table.States (142), 11, Reduce, 40, 2,  8, attribute_declaration_2'Access);
      Add_Action (Table.States (142), 15, Reduce, 40, 2,  8, attribute_declaration_2'Access);
      Add_Action (Table.States (142), 17, Reduce, 40, 2,  8, attribute_declaration_2'Access);
      Add_Action (Table.States (142), 22, Reduce, 40, 2,  8, attribute_declaration_2'Access);
      Add_Action (Table.States (142), 24, Reduce, 40, 2,  8, attribute_declaration_2'Access);
      Add_Action (Table.States (142), 35, Reduce, 40, 2,  8, attribute_declaration_2'Access);
      Add_Error (Table.States (142));
      Add_Action (Table.States (143), 5, Reduce, 40, 1,  8, attribute_declaration_1'Access);
      Add_Action (Table.States (143), 7, Reduce, 40, 1,  8, attribute_declaration_1'Access);
      Add_Action (Table.States (143), 11, Reduce, 40, 1,  8, attribute_declaration_1'Access);
      Add_Action (Table.States (143), 15, Reduce, 40, 1,  8, attribute_declaration_1'Access);
      Add_Action (Table.States (143), 17, Reduce, 40, 1,  8, attribute_declaration_1'Access);
      Add_Action (Table.States (143), 22, Reduce, 40, 1,  8, attribute_declaration_1'Access);
      Add_Action (Table.States (143), 24, Reduce, 40, 1,  8, attribute_declaration_1'Access);
      Add_Action (Table.States (143), 35, Reduce, 40, 1,  8, attribute_declaration_1'Access);
      Add_Error (Table.States (143));
      Add_Action (Table.States (144), 5, Reduce, 60, 0,  9, package_extension_0'Access);
      Add_Action (Table.States (144), 7, Reduce, 60, 0,  9, package_extension_0'Access);
      Add_Action (Table.States (144), 11, Reduce, 60, 0,  9, package_extension_0'Access);
      Add_Action (Table.States (144), 15, Reduce, 60, 0,  9, package_extension_0'Access);
      Add_Action (Table.States (144), 17, Reduce, 60, 0,  9, package_extension_0'Access);
      Add_Action (Table.States (144), 22, Reduce, 60, 0,  9, package_extension_0'Access);
      Add_Action (Table.States (144), 24, Reduce, 60, 0,  9, package_extension_0'Access);
      Add_Action (Table.States (144), 35, Reduce, 60, 0,  9, package_extension_0'Access);
      Add_Error (Table.States (144));

      WisiToken.Parser.LR.Parser.New_Parser
        (Parser,
         Lexer.New_Lexer (Semantic_State.Trace),
         Table,
         Semantic_State,
         Max_Parallel         => 15,
         First_Parser_Label   => 0,
         Terminate_Same_State => True);
   end Create_Parser;
end Gpr_Process;
