with Gen_Parser_Run_Counted_GNAT_OS_Lib;
with Identifier_List_Name_Conflict;
procedure Identifier_List_Name_Conflict_Run is new Gen_Parser_Run_Counted_GNAT_OS_Lib
  (Identifier_List_Name_Conflict.Create_Parser);
