--  Abstract :
--
--  Runtime operations for Ada code generated by wisi-output_ada_emacs
--
--  Copyright (C) 2014, 2015, 2017  All Rights Reserved.
--
--  This program is free software; you can redistribute it and/or
--  modify it under terms of the GNU General Public License as
--  published by the Free Software Foundation; either version 3, or (at
--  your option) any later version. This program is distributed in the
--  hope that it will be useful, but WITHOUT ANY WARRANTY; without even
--  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
--  PURPOSE. See the GNU General Public License for more details. You
--  should have received a copy of the GNU General Public License
--  distributed with this program; see file COPYING. If not, write to
--  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston,
--  MA 02110-1335, USA.

pragma License (GPL);

generic
package FastToken.Token.Wisi_Process_Runtime is

   function To_Code (Nonterm : in Nonterminal_ID) return String;

   function To_Codes (Tokens : in List.Instance) return String;
   --  Return Tokens as `wisi-tokens' in Emacs ada-mode process interface format.

end FastToken.Token.Wisi_Process_Runtime;
