<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<TITLE>CVS log for arm/source/pre_locales.mss</TITLE>
<h1><font color="#008000">CVS log for arm/source/pre_locales.mss</font></h1>
<div style="font-size: 120%; margin-top: 1.0em; margin-bottom: 0.5em">
<img src="/icons/back.gif" style="float: left">
<a href="/cgi-bin/cvsweb.cgi/arm/source/">to arm/source/</a></div>
<div style="margin-top: 0.5em; margin-bottom: 0.7em">
<a href="#diff">Request differences between arbitrary revisions</a></div>
<hr noshade>
<span style="font-size: 120%"><b><a href="/cgi-bin/cvsweb.cgi/arm/source/pre_locales.mss?rev=1.6">1.6</a></b></span><br>
Modified <i>2011/11/01 05:34:04</i>
by <i>randy</i> with line changes <i>+3 -3</i><br>
CVS Tags: <b>HEAD, Amend2_D14</b><br>
<a href="/cgi-bin/cvsweb.cgi/arm/source/pre_locales.mss?diffbase=1.5&rev=1.6">Differences from 1.5</a><br>
<div style="font-family: sans-serif; margin-top: 1.0em; margin-bottom: 0.5em">
Various corrections from ARG editorial reviews; Amendment-Standard comparison tool;
and spell checking (thanks to Dan Eilers).
</div><hr noshade>
<span style="font-size: 120%"><b><a href="/cgi-bin/cvsweb.cgi/arm/source/pre_locales.mss?rev=1.5">1.5</a></b></span><br>
Modified <i>2011/10/21 06:41:25</i>
by <i>randy</i> with line changes <i>+15 -15</i><br>
<a href="/cgi-bin/cvsweb.cgi/arm/source/pre_locales.mss?diffbase=1.4&rev=1.5">Differences from 1.4</a><br>
<div style="font-family: sans-serif; margin-top: 1.0em; margin-bottom: 0.5em">
Various editorial fixes, along with uses of new commands and parameters.
</div><hr noshade>
<span style="font-size: 120%"><b><a href="/cgi-bin/cvsweb.cgi/arm/source/pre_locales.mss?rev=1.4">1.4</a></b></span><br>
Modified <i>2011/04/07 06:18:37</i>
by <i>randy</i> with line changes <i>+10 -10</i><br>
CVS Tags: <b>Amend2_D13, Amend2_D12</b><br>
<a href="/cgi-bin/cvsweb.cgi/arm/source/pre_locales.mss?diffbase=1.3&rev=1.4">Differences from 1.3</a><br>
<div style="font-family: sans-serif; margin-top: 1.0em; margin-bottom: 0.5em">
Applied various editorial review changes and updates to a few AIs.
</div><hr noshade>
<span style="font-size: 120%"><b><a href="/cgi-bin/cvsweb.cgi/arm/source/pre_locales.mss?rev=1.3">1.3</a></b></span><br>
Modified <i>2010/11/25 03:11:50</i>
by <i>randy</i> with line changes <i>+13 -5</i><br>
<a href="/cgi-bin/cvsweb.cgi/arm/source/pre_locales.mss?diffbase=1.2&rev=1.3">Differences from 1.2</a><br>
<div style="font-family: sans-serif; margin-top: 1.0em; margin-bottom: 0.5em">
Various updates, mostly related to ARG meeting #42.
</div><hr noshade>
<span style="font-size: 120%"><b><a href="/cgi-bin/cvsweb.cgi/arm/source/pre_locales.mss?rev=1.2">1.2</a></b></span><br>
Modified <i>2010/10/15 07:05:38</i>
by <i>randy</i> with line changes <i>+9 -9</i><br>
<a href="/cgi-bin/cvsweb.cgi/arm/source/pre_locales.mss?diffbase=1.1&rev=1.2">Differences from 1.1</a><br>
<div style="font-family: sans-serif; margin-top: 1.0em; margin-bottom: 0.5em">
Editorial changes from a number of people.
</div><hr noshade>
<span style="font-size: 120%"><b><a href="/cgi-bin/cvsweb.cgi/arm/source/pre_locales.mss?rev=1.1">1.1</a></b></span><br>
Modified <i>2010/08/13 05:23:14</i>
by <i>randy</i><br>
CVS Tags: <b>Amend2_10</b><br>
<div style="font-family: sans-serif; margin-top: 1.0em; margin-bottom: 0.5em">
Added text for various AIs approved in Valencia.
</div>
<hr noshade>
<p><a name="diff">This form</a> allows you to request differences between any
two revisions of a file, by number or by tag.</p>
<form method="GET" action="/cgi-bin/cvsweb.cgi/arm/source/pre_locales.mss">
Differences between
<select name="diffbase">
<option selected value="1.6">1.6
<option value="1.5">1.5
<option value="1.4">1.4
<option value="1.3">1.3
<option value="1.2">1.2
<option value="1.1">1.1
<option value="1.6">HEAD
<option value="1.6">Amend2_D14
<option value="1.4">Amend2_D13
<option value="1.4">Amend2_D12
<option value="1.1">Amend2_10
</select>
<select name="rev">
<option selected value="1.6">1.6
<option value="1.5">1.5
<option value="1.4">1.4
<option value="1.3">1.3
<option value="1.2">1.2
<option value="1.1">1.1
<option value="1.6">HEAD
<option value="1.6">Amend2_D14
<option value="1.4">Amend2_D13
<option value="1.4">Amend2_D12
<option value="1.1">Amend2_10
</select>
<div style="margin-top: 0.5em"><input type="submit" value="Get Differences"></div>
</form>
<hr><address>Questions? Ask the <a href="/mailto.html">ACAA Technical Agent</a><br></address>
</BODY></HTML>
